asyn:
  use: false
attack:
  alpha_TV: 0.001
  alpha_prop_loss: 0
  attack_method: ''
  attacker_id: -1
  classifier_PIA: randomforest
  edge_num: 100
  edge_path: edge_data/
  freq: 10
  info_diff_type: l2
  inject_round: 0
  insert_round: 100000
  label_type: dirty
  max_ite: 400
  mean:
  - 0.1307
  mia_is_simulate_in: false
  mia_simulate_in_round: 20
  pgd_eps: 2
  pgd_lr: 0.1
  pgd_poisoning: false
  poison_ratio: 0.5
  reconstruct_lr: 0.01
  reconstruct_optim: Adam
  scale_para: 1.0
  scale_poisoning: false
  self_epoch: 6
  self_lr: 0.05
  self_opt: false
  setting: fix
  std:
  - 0.3081
  target_label_ind: -1
  trigger_path: trigger/
  trigger_type: edge
backend: torch
cfg_file: ''
criterion:
  type: CrossEntropyLoss
data:
  args: []
  batch_size: 64
  cSBM_phi:
  - 0.5
  - 0.5
  - 0.5
  consistent_label_distribution: false
  drop_last: false
  loader: ''
  num_steps: 30
  num_workers: 0
  pre_transform: []
  quadratic:
    dim: 1
    max_curv: 12.5
    min_curv: 0.02
  root: data/
  save_data: false
  server_holds_all: false
  shuffle: true
  sizes:
  - 10
  - 5
  splits:
  - 0.8
  - 0.1
  - 0.1
  splitter: random
  splitter_args: []
  subsample: 1.0
  target_transform: []
  transform: []
  type: cora
  walk_length: 2
dataloader:
  batch_size: 1
  drop_last: false
  num_steps: 30
  num_workers: 0
  pin_memory: true
  shuffle: true
  sizes:
  - 10
  - 5
  theta: -1
  type: pyg
  walk_length: 2
device: 0
distribute:
  use: false
early_stop:
  delta: 0.0
  improve_indicator_mode: best
  patience: 200
  the_smaller_the_better: false
eval:
  best_res_update_round_wise_key: val_acc
  count_flops: true
  freq: 1
  metrics:
  - acc
  - correct
  monitoring: []
  report:
  - weighted_avg
  - avg
  - fairness
  - raw
  split:
  - test
  - val
expname: fedgsl_gnn_fedgsl_gcn_on_cora_lr0.001_lstep3
expname_tag: ''
federate:
  client_num: 3
  data_weighted_aggr: false
  ignore_weight: false
  join_in_info: []
  make_global_eval: false
  merge_test_data: false
  method: fedgsl
  mode: standalone
  online_aggr: false
  resource_info_file: ''
  restore_from: ''
  sample_client_num: 3
  sample_client_rate: -1.0
  sampler: uniform
  save_to: ''
  share_local_model: false
  total_round_num: 800
  unseen_clients_rate: 0.0
  use_diff: false
  use_ss: false
fedgsl: {}
fedopt:
  use: false
fedprox:
  use: false
fedsageplus:
  a: 1.0
  b: 1.0
  c: 1.0
  fedgen_epoch: 200
  gen_hidden: 128
  hide_portion: 0.5
  loc_epoch: 1
  num_pred: 5
finetune:
  batch_or_epoch: epoch
  before_eval: false
  freeze_param: ''
  local_update_steps: 1
  optimizer:
    lr: 0.1
    type: SGD
  scheduler:
    type: ''
flitplus:
  factor_ema: 0.8
  lambdavat: 0.5
  tmpFed: 0.5
  weightReg: 1.0
gcflplus:
  EPS_1: 0.05
  EPS_2: 0.1
  seq_length: 5
  standardize: false
grad:
  grad_clip: -1.0
hpo:
  fedex:
    cutoff: 0.0
    diff: false
    eta0: -1.0
    flatten_ss: true
    gamma: 0.0
    sched: auto
    ss: ''
    use: false
  init_cand_num: 16
  larger_better: false
  metric: client_summarized_weighted_avg.val_loss
  num_workers: 0
  pbt:
    max_stage: 5
    perf_threshold: 0.1
  scheduler: rs
  sha:
    budgets: []
    elim_rate: 3
    iter: 0
  ss: ''
  table:
    eps: 0.1
    idx: 0
    num: 27
  working_folder: hpo
model:
  dropout: 0.5
  embed_size: 8
  fedgsl:
    LDP_lambda: 0.015
    add_noise: false
    glob_gnn_outsize: 64
    gnn_layer: 2
    gpr_layer: 10
    gsl_clip_grad: false
    gsl_gnn_dropout: 0.5
    gsl_gnn_hids: 64
    gsl_mlp_layer: 2
    gsl_optimizer_type: Adam
    k: 10
    loc_gnn_hid: 64
    loc_gnn_outsize: 256
    loc_mlp_hids: 64
    loc_mlp_layer: 1
    lr_AE: 0.2
    node_dim: 64
    pretrain_epoch: 200
    pretrain_out_channels: 64
    server_lr: 0.001
    update_RawNodeFeature: false
  fedpub:
    agg_norm: exp
    backbone: GNN
    clsf_mask_one: false
    cluster: true
    l1: 0.001
    laye_mask_one: false
    loc_l2: 0.001
    mask_aggr: false
    mask_drop: false
    mask_drop_ratio: 0.5
    mask_noise: false
    mask_rank: -1
    n_feat: 1433
    n_proxy: 5
    no_clsf_mask: false
    norm_scale: 10
    task: Cora_CC_total_0.2_HET
  graph_pooling: mean
  hidden: 64
  in_channels: 0
  input_shape: []
  layer: 2
  model_num_per_trainer: 1
  num_item: 0
  num_user: 0
  out_channels: 7
  task: node
  type: gnn_fedgsl_gcn
  use_bias: true
nbafl:
  use: false
outdir: exp\fedgsl_gnn_fedgsl_gcn_on_cora_lr0.001_lstep3\sub_exp_20221130160942
personalization:
  K: 5
  beta: 1.0
  local_param: []
  local_update_steps: 3
  lr: 0.001
  regular_weight: 0.1
  share_non_trainable_para: false
print_decimal_digits: 6
regularizer:
  mu: 0.0
  type: ''
seed: 0
sgdmf:
  use: false
train:
  batch_or_epoch: batch
  local_update_steps: 3
  optimizer:
    lr: 0.001
    type: SGD
    weight_decay: 0.0005
  scheduler:
    type: ''
trainer:
  type: fedpub_trainer
use_gpu: true
verbose: 1
vertical:
  use: false
wandb:
  use: false
xgb_base:
  use: false

